# Context : Brain stroke

A stroke is a medical condition in which poor blood flow to the brain causes cell death.The main risk factor for stroke is high blood pressure. Other risk factors include high blood cholesterol, tobacco smoking, obesity, diabetes mellitus, a previous TIA, end-stage kidney disease, and atrial fibrillation. In this dataset, we are going to predict the person has brain stroke or not using the features like gender, age, hypertension, heart disease, ever married, work type, residence type, avg glucose level, bmi, smoking status.  

# Importing neccessary libraries

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
df= pd.read_csv('/content/drive/MyDrive/Adaboost/brain_stroke.csv')
df.head()

gender   age  hypertension  heart_disease ever_married      work_type  \
0    Male  67.0             0              1          Yes        Private   
1    Male  80.0             0              1          Yes        Private   
2  Female  49.0             0              0          Yes        Private   
3  Female  79.0             1              0          Yes  Self-employed   
4    Male  81.0             0              0          Yes        Private   

  Residence_type  avg_glucose_level   bmi   smoking_status  stroke  
0          Urban             228.69  36.6  formerly smoked       1  
1          Rural             105.92  32.5     never smoked       1  
2          Urban             171.23  34.4           smokes       1  
3          Rural             174.12  24.0     never smoked       1  
4          Urban             186.21  29.0  formerly smoked       1

## Summarizing the dataset

In [ ]:
df.shape

(4981, 11)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   gender             4981 non-null   object 
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64  
 3   heart_disease      4981 non-null   int64  
 4   ever_married       4981 non-null   object 
 5   work_type          4981 non-null   object 
 6   Residence_type     4981 non-null   object 
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object 
 10  stroke             4981 non-null   int64  
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB


In [ ]:
## There are no null values present in the dataset. But the columns having both categorical and numerical columns

In [ ]:
df.describe()

age  hypertension  heart_disease  avg_glucose_level  \
count  4981.000000   4981.000000    4981.000000        4981.000000   
mean     43.419859      0.096165       0.055210         105.943562   
std      22.662755      0.294848       0.228412          45.075373   
min       0.080000      0.000000       0.000000          55.120000   
25%      25.000000      0.000000       0.000000          77.230000   
50%      45.000000      0.000000       0.000000          91.850000   
75%      61.000000      0.000000       0.000000         113.860000   
max      82.000000      1.000000       1.000000         271.740000   

               bmi       stroke  
count  4981.000000  4981.000000  
mean     28.498173     0.049789  
std       6.790464     0.217531  
min      14.000000     0.000000  
25%      23.700000     0.000000  
50%      28.100000     0.000000  
75%      32.600000     0.000000  
max      48.900000     1.000000

## Data processing

In [ ]:
df.isnull().sum()

gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

There are no null values present in the dataset

In [ ]:
df.dtypes

gender                object
age                  float64
hypertension           int64
heart_disease          int64
ever_married          object
work_type             object
Residence_type        object
avg_glucose_level    float64
bmi                  float64
smoking_status        object
stroke                 int64
dtype: object

There are 5 columns which are object columns, that needs to be converted to numerical. Lets have a look at each object column.

In [ ]:
df['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [ ]:
df['ever_married'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
df['work_type'].unique()

array(['Private', 'Self-employed', 'Govt_job', 'children'], dtype=object)

In [ ]:
df['Residence_type'].unique()

array(['Urban', 'Rural'], dtype=object)

In [ ]:
df['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

## EXPLORATORY DATA ANLAYSIS

In [ ]:
# Here ever_married, work_type and Residence_type columns are no way related to the target column. so we can drop those columns.

df= df.drop(['ever_married','work_type','Residence_type'], axis=1)
df.head()

gender   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0    Male  67.0             0              1             228.69  36.6   
1    Male  80.0             0              1             105.92  32.5   
2  Female  49.0             0              0             171.23  34.4   
3  Female  79.0             1              0             174.12  24.0   
4    Male  81.0             0              0             186.21  29.0   

    smoking_status  stroke  
0  formerly smoked       1  
1     never smoked       1  
2           smokes       1  
3     never smoked       1  
4  formerly smoked       1

In [ ]:
# Next convert categorical columns to numerical columns

Label_encoder= LabelEncoder()
df['gender']= Label_encoder.fit_transform(df['gender'])
df.head()

gender   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0       1  67.0             0              1             228.69  36.6   
1       1  80.0             0              1             105.92  32.5   
2       0  49.0             0              0             171.23  34.4   
3       0  79.0             1              0             174.12  24.0   
4       1  81.0             0              0             186.21  29.0   

    smoking_status  stroke  
0  formerly smoked       1  
1     never smoked       1  
2           smokes       1  
3     never smoked       1  
4  formerly smoked       1

In [ ]:
df['smoking_status'].unique()

array(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],
      dtype=object)

In [ ]:
df['smoking_status'].replace(['formerly smoked', 'never smoked', 'smokes', 'Unknown'],[0,1,2,3], inplace=True)
df.head()

gender   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0       1  67.0             0              1             228.69  36.6   
1       1  80.0             0              1             105.92  32.5   
2       0  49.0             0              0             171.23  34.4   
3       0  79.0             1              0             174.12  24.0   
4       1  81.0             0              0             186.21  29.0   

   smoking_status  stroke  
0               0       1  
1               1       1  
2               2       1  
3               1       1  
4               0       1

In [ ]:
df.dtypes

gender                 int64
age                  float64
hypertension           int64
heart_disease          int64
avg_glucose_level    float64
bmi                  float64
smoking_status         int64
stroke                 int64
dtype: object

Now our dataset is ready for modeling.

## Segregating the dataset into X and Y

In [ ]:
df.head()

gender   age  hypertension  heart_disease  avg_glucose_level   bmi  \
0       1  67.0             0              1             228.69  36.6   
1       1  80.0             0              1             105.92  32.5   
2       0  49.0             0              0             171.23  34.4   
3       0  79.0             1              0             174.12  24.0   
4       1  81.0             0              0             186.21  29.0   

   smoking_status  stroke  
0               0       1  
1               1       1  
2               2       1  
3               1       1  
4               0       1

In [ ]:
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2, random_state=45)

In [ ]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3984, 7), (997, 7), (3984,), (997,))

In [ ]:
# Loading the model
model=AdaBoostClassifier()
model

AdaBoostClassifier()

In [ ]:
# Training the model

model.fit(x_train,y_train)

AdaBoostClassifier()

In [ ]:
# Predicting the result using the trained model

y_pred= model.predict(x_test)

In [ ]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
# calculation the accuracy

accuracy= accuracy_score(y_test,y_pred)
accuracy

0.9518555667001003

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.96      0.99      0.98       954
           1       0.00      0.00      0.00        43

    accuracy                           0.95       997
   macro avg       0.48      0.50      0.49       997
weighted avg       0.92      0.95      0.93       997



In [ ]:
df['stroke'].value_counts()

stroke
0    4733
1     248
Name: count, dtype: int64

In [ ]:
248/4981

0.049789198956032926

## Predicting the output for a single output using trained model

In [ ]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
x_test[0]

array([  0.  ,  66.  ,   0.  ,   0.  , 102.73,  35.  ,   0.  ])

In [ ]:
x_test[0].shape

(7,)

In [ ]:
x_test[0].reshape(1,7)

array([[  0.  ,  66.  ,   0.  ,   0.  , 102.73,  35.  ,   0.  ]])

In [ ]:
x_test[0].reshape(1,7).shape

(1, 7)

In [ ]:
model.predict(x_test[0].reshape(1,7))

array([0])